#ifndef VK_MODERN_UI_LAYER_HPP
#define VK_MODERN_UI_LAYER_HPP

#include <memory>
#include <mutex>
#include <atomic>
#include <cstring>
#include <vulkan/vulkan.h>
#include <vulkan/vk_layer.h>

// On Linux/Unix platforms, VK_LAYER_EXPORT is mapped to default visibility attribute.
#ifndef VK_LAYER_EXPORT
#if defined(_WIN32)
#define VK_LAYER_EXPORT __declspec(dllexport)
#else
#define VK_LAYER_EXPORT __attribute__((visibility("default")))
#endif
#endif

// ============================================================================
// 1. DATA STRUCTURES
// ============================================================================

// Game Data Structure (populated by the Game Data Read Thread)
struct GameData {
    uint32_t frame_id = 0;
    float player_x = 0.0f;
    float player_y = 0.0f;
    float player_z = 0.0f;
    uint32_t player_hp = 100;
    uint32_t player_mp = 100;
    char target_name[48] = "None";
    uint64_t timestamp = 0;
};

// UI Render Command Structure (generated by the JS/HTML Thread)
struct UIRenderData {
    uint32_t frame_id = 0;

    struct UIElement {
        char tag[16] = "";          // e.g. "div", "button", "health-bar"
        float x = 0.0f;
        float y = 0.0f;
        float width = 0.0f;
        float height = 0.0f;
        uint32_t color = 0xFFFFFFFF; // RGBA8
        char text[128] = "";
    };

    uint32_t element_count = 0;
    UIElement elements[32];
    uint64_t render_timestamp = 0;
};

// Vulkan Draw State Structure (generated by Vulkan Rendering Thread for Hook_QueuePresentKHR)
struct VulkanDrawState {
    uint32_t ui_frame_id = 0;
    uint32_t draw_call_count = 0;

    struct DrawCall {
        char element_tag[16] = "";
        float rect_x = 0.0f;
        float rect_y = 0.0f;
        float rect_w = 0.0f;
        float rect_h = 0.0f;
        uint32_t color = 0;
        char text_content[128] = "";
    };

    DrawCall draw_calls[32];
    uint64_t compiled_timestamp = 0;
};

// ============================================================================
// 2. POINTER-SWAP DOUBLE BUFFER TEMPLATE
// ============================================================================
// Implements highly-efficient triple-buffered double pointer swapping.
// Producer writes to a private buffer, then swaps with the shared buffer.
// Consumer reads from its private buffer, and swaps with the shared buffer if new data is available.
// This guarantees that Producer and Consumer never block or experience race conditions on the same buffer.
template <typename T>
class PointerSwapBuffer {
public:
    PointerSwapBuffer() {
        producer_buf = std::make_unique<T>();
        shared_buf = std::make_unique<T>();
        consumer_buf = std::make_unique<T>();
        new_data_available.store(false, std::memory_order_release);
    }

    // Producer gets exclusive access to write to its private buffer.
    // No lock is required during writing.
    T* get_producer_buffer() {
        return producer_buf.get();
    }

    // Producer publishes its private buffer to the shared buffer.
    // This is a fast pointer swap under a lightweight mutex.
    void publish() {
        std::lock_guard<std::mutex> lock(mtx);
        producer_buf.swap(shared_buf);
        new_data_available.store(true, std::memory_order_release);
    }

    // Consumer gets access to the latest published buffer.
    // If new data is available, it swaps its private buffer with the shared buffer.
    // No lock is required during reading after this call.
    // Returns true if a swap happened (new data was acquired), false otherwise.
    bool acquire_latest() {
        if (new_data_available.load(std::memory_order_acquire)) {
            std::lock_guard<std::mutex> lock(mtx);
            consumer_buf.swap(shared_buf);
            new_data_available.store(false, std::memory_order_release);
            return true;
        }
        return false;
    }

    // Consumer gets exclusive access to read its private buffer.
    T* get_consumer_buffer() {
        return consumer_buf.get();
    }

private:
    std::unique_ptr<T> producer_buf;
    std::unique_ptr<T> shared_buf;
    std::unique_ptr<T> consumer_buf;
    std::mutex mtx;
    std::atomic<bool> new_data_available;
};

// ============================================================================
// 3. GLOBAL BUFFERS DECLARATION (STRICT SPSC PIPELINE SEGMENTS)
// ============================================================================
// Stage 1: GameData Thread (Producer) -> g_game_data_pub -> JS/HTML Thread (Consumer)
extern PointerSwapBuffer<GameData> g_game_data_pub;

// Stage 2: JS/HTML Thread (Producer) -> g_ui_render_pub -> Vulkan Rendering Thread (Consumer)
extern PointerSwapBuffer<UIRenderData> g_ui_render_pub;

// Stage 3: Vulkan Rendering Thread (Producer) -> g_vk_draw_state_pub -> Hook_QueuePresentKHR (Consumer)
extern PointerSwapBuffer<VulkanDrawState> g_vk_draw_state_pub;

// ============================================================================
// 4. BACKGROUND THREAD LIFE-CYCLE MANAGEMENT
// ============================================================================
void StartModernUIThreads();
void StopModernUIThreads();
bool AreThreadsRunning();

// ============================================================================
// 5. VULKAN LAYER INTERCEPT FUNCTIONS
// ============================================================================
#ifdef __cplusplus
extern "C" {
#endif

// Layer entry point for standard Vulkan loader interface negotiation
VK_LAYER_EXPORT VkResult VKAPI_CALL vkNegotiateLoaderLayerInterfaceVersion(VkNegotiateLayerInterface *pVersionStruct);

// Layer entry points for function resolution
VK_LAYER_EXPORT PFN_vkVoidFunction VKAPI_CALL vkGetInstanceProcAddr(VkInstance instance, const char* pName);
VK_LAYER_EXPORT PFN_vkVoidFunction VKAPI_CALL vkGetDeviceProcAddr(VkDevice device, const char* pName);

#ifdef __cplusplus
}
#endif

#endif // VK_MODERN_UI_LAYER_HPP
